#!/usr/bin/env python3
"""
File-oriented helper for storing generated teacher skills.
"""

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def _ensure_utf8_stdout() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")


class SkillWriter:
    """Create and update the teacher skill directory structure."""

    def __init__(self, base_dir: str = "./teachers"):
        self.base_dir = Path(base_dir)
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def create_skill(self, slug: str, skill_data: Dict[str, Any]) -> Dict[str, Any]:
        skill_dir = self.base_dir / slug
        skill_dir.mkdir(parents=True, exist_ok=True)

        documents = skill_data.get("documents", {})
        teaching_content = documents.get("teaching", "# Teaching\n\n[Generated by AI]")
        teacher_content = documents.get("teacher", "# Teacher\n\n[Generated by AI]")
        knowledge_content = documents.get("knowledge", "# Knowledge\n\n[Generated by AI]")

        teaching_path = skill_dir / "teaching.md"
        teacher_path = skill_dir / "teacher.md"
        knowledge_path = skill_dir / "knowledge.md"

        teaching_path.write_text(teaching_content, encoding="utf-8")
        teacher_path.write_text(teacher_content, encoding="utf-8")
        knowledge_path.write_text(knowledge_content, encoding="utf-8")

        teacher_info = skill_data.get("teacher_info", {})
        meta = {
            "name": teacher_info.get("name", slug),
            "slug": slug,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "updated_at": datetime.now(timezone.utc).isoformat(),
            "version": "v1",
            "generated_by": "teacher-skill-engine",
        }
        meta_path = skill_dir / "meta.json"
        meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")

        skill_md_path = skill_dir / "SKILL.md"
        skill_md_path.write_text(
            self._generate_skill_md(slug, meta, teaching_content, teacher_content, knowledge_content),
            encoding="utf-8",
        )

        logger.info("Created skill at %s", skill_dir)
        return {
            "status": "success",
            "slug": slug,
            "skill_dir": str(skill_dir.resolve()),
            "files_created": [
                str(teaching_path.resolve()),
                str(teacher_path.resolve()),
                str(knowledge_path.resolve()),
                str(meta_path.resolve()),
                str(skill_md_path.resolve()),
            ],
        }

    def update_skill(self, slug: str, updated_doc: str, doc_type: str = "teaching") -> Dict[str, Any]:
        skill_dir = self.base_dir / slug
        if not skill_dir.exists():
            return {"status": "error", "message": f"Skill {slug} does not exist"}

        supported = {"teaching", "teacher", "knowledge"}
        if doc_type not in supported:
            return {"status": "error", "message": f"Unsupported doc_type: {doc_type}"}

        doc_path = skill_dir / f"{doc_type}.md"
        doc_path.write_text(updated_doc, encoding="utf-8")

        meta_path = skill_dir / "meta.json"
        if meta_path.exists():
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            meta["updated_at"] = datetime.now(timezone.utc).isoformat()
            meta["last_update_type"] = doc_type
            meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")

        self._regenerate_skill_md(skill_dir)
        return {
            "status": "success",
            "slug": slug,
            "updated_doc": doc_type,
            "document_length": len(updated_doc),
        }

    def list_skills(self) -> List[Dict[str, Any]]:
        skills: List[Dict[str, Any]] = []
        for skill_dir in self.base_dir.iterdir():
            if not skill_dir.is_dir() or skill_dir.name.startswith("."):
                continue

            meta_path = skill_dir / "meta.json"
            if not meta_path.exists():
                continue

            try:
                meta = json.loads(meta_path.read_text(encoding="utf-8"))
                skills.append(
                    {
                        "slug": skill_dir.name,
                        "name": meta.get("name", skill_dir.name),
                        "created_at": meta.get("created_at"),
                        "updated_at": meta.get("updated_at"),
                        "version": meta.get("version", "v1"),
                        "skill_dir": str(skill_dir.resolve()),
                    }
                )
            except Exception as exc:
                logger.error("Failed to read %s: %s", meta_path, exc)

        skills.sort(key=lambda item: item.get("updated_at", ""), reverse=True)
        return skills

    def _generate_skill_md(
        self,
        slug: str,
        meta: Dict[str, Any],
        teaching_content: str,
        teacher_content: str,
        knowledge_content: str,
    ) -> str:
        return f"""---
name: teacher-{slug}
description: "{meta.get('name', slug)} - teacher skill"
user-invocable: true
---

# {meta.get('name', slug)}

## Teaching
{teaching_content}

## Teacher
{teacher_content}

## Knowledge
{knowledge_content}

## Usage

- Full skill: `/{slug}`
- Teaching only: `/{slug}-teaching`
- Teacher style only: `/{slug}-teacher`
- Knowledge only: `/{slug}-knowledge`

Version: {meta.get('version', 'v1')}
Created at: {meta.get('created_at', 'unknown')}
Updated at: {meta.get('updated_at', 'unknown')}
"""

    def _regenerate_skill_md(self, skill_dir: Path) -> None:
        meta_path = skill_dir / "meta.json"
        teaching_path = skill_dir / "teaching.md"
        teacher_path = skill_dir / "teacher.md"
        knowledge_path = skill_dir / "knowledge.md"
        if not all(path.exists() for path in [meta_path, teaching_path, teacher_path, knowledge_path]):
            return

        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        teaching_content = teaching_path.read_text(encoding="utf-8")
        teacher_content = teacher_path.read_text(encoding="utf-8")
        knowledge_content = knowledge_path.read_text(encoding="utf-8")
        (skill_dir / "SKILL.md").write_text(
            self._generate_skill_md(skill_dir.name, meta, teaching_content, teacher_content, knowledge_content),
            encoding="utf-8",
        )


def main() -> int:
    _ensure_utf8_stdout()

    parser = argparse.ArgumentParser(description="Manage teacher skill files")
    parser.add_argument("--action", choices=["list"], default="list")
    parser.add_argument("--base-dir", default="./teachers")
    args = parser.parse_args()

    writer = SkillWriter(base_dir=args.base_dir)

    if args.action == "list":
        skills = writer.list_skills()
        print(json.dumps(skills, ensure_ascii=False, indent=2))
        return 0

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
